=== sbergot/salvageunion-data/schemas/equipment.schema.json
{
  "$schema": "https://json-schema.org/draft-07/schema",
  "type": "array",
  "items": {
    "type": "object",
    "additionalProperties": false,
    "properties": {
      "name": { "type": "string" },
      "techLevel": { "type": "number" },
      "traits": { "$ref": "shared/common.schema.json#/definitions/traits" },
      "description": {
        "type": "string"
      },
      "notes": {
        "type": "string"
      },
      "activationCost": { "$ref": "shared/common.schema.json#/definitions/activationCost" },
      "range": { "$ref": "shared/enums.schema.json#/definitions/range" },
      "damage": { "$ref": "shared/common.schema.json#/definitions/damage" },
      "actionType": { "$ref": "shared/enums.schema.json#/definitions/actionType" },
      "actions": {
        "type": "array",
        "items": { "$ref": "shared/objects.schema.json#/definitions/action" }
      }
    }
  }
}

=== sbergot/salvageunion-data/data/equipment.json
[
  {
    "name": "First Aid Kit",
    "techLevel": 1,
    "traits": [
      {
        "type": "uses",
        "amount": 3
      }
    ],
    "range": "Close",
    "description": "This set of bandages, plasters, gauze, painkillers, and antiseptics allows you to patch up wounds in the field. A target creature of your choice in Range regains 3 Hit Points. If they were on 0 Hit Points this restores them to consciousness with 3 HP.",
    "notes": "*Union Safety Guideline 305.15 recommends each Union Crawler salvage crew equip a First Aid Kit for all active field work.*"
  },
  {
    "name": "Handheld Riveting Gun",
    "techLevel": 1,
    "range": "Close",
    "description": "This pocket-sized riveting gun can make basic repairs in the field.",
    "actions": [
      {
        "name": "Patch",
        "actionType": "Turn",
        "activationCost": 2,
        "range": "Close",
        "description": "When activated, a target Mech or Vehicle of your choice in Range with at least 1 SP regains 2 SP."
      },
      {
        "name": "System Repair",
        "actionType": "Short",
        "activationCost": 2,
        "range": "Close",
        "description": "You repair a damaged Tech 1 System or Module in Range to Intact Condition. It is now usable."
      },
      {
        "name": "Chassis Repair",
        "actionType": "Long",
        "activationCost": 4,
        "range": "Close",
        "description": "You repair a damaged Tech 1 Mech Chassis or Vehicle in Range to Intact Condition. It is now usable with 1 SP."
      }
    ]
  },
  {
    "name": "Heavy Duty Torch",
    "techLevel": 1,
    "actionType": "Free",
    "range": "Close",
    "description": "A handheld workerâ€™s torch that runs on a rechargeable lithium-ion battery. This lights up an area in Close Range of the Pilot, allowing them to see more clearly in dark or foggy conditions."
  },
  {
    "name": "High Tensile Wire",
    "techLevel": 1,
    "traits": [
      {
        "type": "rigging"
      }
    ],
    "actionType": "Turn",
    "range": "Close",
    "description": "Strong and durable wire, with multiple potential creative applications.This can be attached to anything within Range, allowing you to climb the wire. It can also be used to aid in the dragging of heavy objects."
  },
  {
    "name": "Improvised Explosive Device",
    "techLevel": 1,
    "traits": [
      {
        "type": "explosive",
        "amount": 1
      },
      {
        "type": "uses",
        "amount": 2
      }
    ],
    "range": "Close",
    "description": "This covers any number of homemade explosives. Exploding powder and bits of shrapnel are easy to find amongst the wastes. An IED can be thrown at a target as an attack. It can also be planted as a proximity mine which triggers when a target comes within Close Range of the IED. In either case, roll an attack as normal to find out what happens.",
    "damage": {
      "type": "SP",
      "amount": 3
    }
  },
  {
    "name": "Improvised Firearm",
    "techLevel": 1,
    "traits": [
      {
        "type": "ballistic"
      },
      {
        "type": "unwieldy"
      }
    ],
    "range": "Close",
    "description": "This covers any number of improvised firearms such as pipe guns, zip guns, and slam guns. The humble boomstick has got many a salvager out of a sticky situation.",
    "damage": {
      "type": "HP",
      "amount": 3
    }
  },
  {
    "name": "Improvised Melee Weapon",
    "techLevel": 1,
    "traits": [
      {
        "type": "melee"
      },
      {
        "type": "silent"
      }
    ],
    "range": "Close",
    "description": "This covers any number of melee weapons from wrenches and hammers to shards of metal and sharpened metal posts. There are a lot of things you can use to bludgeon, stab, or otherwise injure someone, to be found in the wastes.",
    "damage": {
      "type": "HP",
      "amount": 2
    }
  },
  {
    "name": "Portable Comms Unit",
    "techLevel": 1,
    "traits": [
      {
        "type": "communicator"
      }
    ],
    "actionType": "Free",
    "range": "Medium",
    "description": "A handheld communications device that uses a radio frequency. This allows you to communicate with anything that has the Communicator Trait within Range."
  },
  {
    "name": "Salvaging Tools",
    "techLevel": 1,
    "traits": [
      {
        "type": "salvaging"
      }
    ],
    "description": "This covers a wide array of tools, from jacks to hammers to angle grinders, that are used in salvaging. This allows your Pilot to salvage in the field, because sometimes you need to get your hands dirty."
  },
  {
    "name": "Flare Gun",
    "techLevel": 2,
    "traits": [
      {
        "type": "uses",
        "amount": 3
      }
    ],
    "actionType": "Turn",
    "range": "Far",
    "description": "A launcher for a flare intended to be used as a distress signal, beacon, or in a pinch, to light up an area. When fired, the flare can be seen from anywhere up to Far Range. It lights up an area within Close Range of its target for 1 hour."
  },
  {
    "name": "Holofoil Tent",
    "techLevel": 2,
    "actionType": "Short",
    "description": "A large, sturdy but light tent made out of a strong, waterproof, and insulating material. The tent can comfortably fit up to five people. Everyone inside the tent suffers no damage or effect from dangerous environmental effects such as radiation storms, cold snaps, or acid rain, and half damage from severe environmental effects such as tornadoes and firestorms."
  },
  {
    "name": "Pistol",
    "techLevel": 2,
    "traits": [
      {
        "type": "ballistic"
      }
    ],
    "range": "Close",
    "description": "This weapon covers a wide variety of standard issue pistols such as revolvers and semi-automatic pistols.",
    "damage": {
      "type": "HP",
      "amount": 3
    }
  },
  {
    "name": "Disposable Camera",
    "techLevel": 2,
    "traits": [
      {
        "type": "uses",
        "amount": 30
      }
    ],
    "actionType": "Turn",
    "range": "Far",
    "description": "A disposable camera that can take up to 30 pictures of anything within Range. These pictures can be developed during Downtime on your Union Crawler and used as a Keepsake."
  },
  {
    "name": "Portable Arc Welder",
    "techLevel": 2,
    "description": "This miniaturised Arc Welder allows you to make improved field repairs to a wide variety of Mechs and parts.",
    "actions": [
      {
        "name": "Patch",
        "actionType": "Turn",
        "activationCost": 2,
        "range": "Close",
        "description": "When activated, a target Mech or Vehicle of your choice in Range with at least 1 SP regains 3 SP."
      },
      {
        "name": "System Repair",
        "actionType": "Short",
        "activationCost": 2,
        "range": "Close",
        "description": "You repair a damaged Tech 1 or 2 System or Module in Range to Intact Condition. It is now usable."
      },
      {
        "name": "Chassis Repair",
        "actionType": "Long",
        "activationCost": 4,
        "range": "Close",
        "description": "You repair a damaged Tech 1 or 2 Mech Chassis or Vehicle in Range to Intact Condition. It is now usable with 1 SP."
      }
    ]
  },
  {
    "name": "Red Laser Pistol",
    "techLevel": 2,
    "traits": [
      {
        "type": "energy"
      }
    ],
    "range": "Close",
    "description": "This weapon covers a wide variety of standard issue handheld lasers such as blasters, phasers, and zap guns.",
    "damage": {
      "type": "HP",
      "amount": 3
    }
  },
  {
    "name": "Rigging Jack",
    "techLevel": 2,
    "traits": [
      {
        "type": "rigging"
      }
    ],
    "description": "This hydraulic jack can aid in the heavy lifting of salvage. The Rigging Jack can carry 1 Scrap upon it."
  },
  {
    "name": "Reinforced Polycarbonate Shield",
    "techLevel": 2,
    "traits": [
      {
        "type": "heavy"
      },
      {
        "type": "shield"
      }
    ],
    "actionType": "Reaction",
    "description": "Typically used in breaching and boarding actions, as well as for riot control, this large shield protects its wearer from harm. When your Pilot is hit by an attack you may destroy the Reinforced Polycarbonate Shield to take half damage from the attack and suffer none of its effects."
  },
  {
    "name": "Green Laser Rifle",
    "techLevel": 3,
    "traits": [
      {
        "type": "energy"
      }
    ],
    "range": "Medium",
    "description": "This weapon covers a wide variety of standard issue shoulder-mounted energy laser rifles such as beam guns, pulse lasers, and ray rifles.",
    "damage": {
      "type": "HP",
      "amount": 5
    }
  },
  {
    "name": "Grenade",
    "techLevel": 3,
    "traits": [
      {
        "type": "explosive",
        "amount": 1
      },
      {
        "type": "uses",
        "amount": 3
      }
    ],
    "range": "Medium",
    "description": "A handheld explosive device that can be thrown towards a target dealing high damage in an area.",
    "damage": {
      "type": "SP",
      "amount": 4
    }
  },
  {
    "name": "Hazard Protection Suit",
    "techLevel": 3,
    "traits": [
      {
        "type": "armor"
      },
      {
        "type": "heavy"
      }
    ],
    "description": "This all-purpose bio-hazard suit can protect you from the ravages of the wastes once you are zipped up all comfy inside. The suit protects you from dangerous environmental hazards such as radiation storms, cold snaps, or acid rain. In addition, you take half damage from any severe environmental hazards such as tornadoes, firestorms, or bubbling pools of toxic waste."
  },
  {
    "name": "Healing Bio-Foam",
    "techLevel": 3,
    "traits": [
      {
        "type": "uses",
        "amount": 3
      }
    ],
    "description": "This canister contains an advanced form of bio-foam that when sprayed on a wound forms a rigid layer of biocomposite polymer, sealing the injury.",
    "actions": [
      {
